---
title: "MUSA508_Project1"
author: "Chi Zhang, Zhijie Zhou"
date: "10/11/2020"
output: 
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    number_sections: false
    theme: lumen
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, results=F, fig.width=11, fig.height=8)
```

## SETUP

```{r results=F}
library(tidyverse)
library(tidycensus)
library(kableExtra)
library(sf)
library(spdep)
library(caret)
library(ckanr)
library(FNN)
library(grid)
library(gridExtra)
library(ggcorrplot)
library(jtools) 
options(scipen=999)
options(tigris_class = "sf")
options(tigris_use_cache = TRUE)

# functions
mapTheme <- function(base_size = 12) {
  theme(
    text = element_text( color = "black"),
    plot.title = element_text(size = 14,colour = "black"),
    plot.subtitle=element_text(face="italic"),
    plot.caption=element_text(hjust=0),
    axis.ticks = element_blank(),
    panel.background = element_blank(),axis.title = element_blank(),
    axis.text = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(colour = "black", fill=NA, size=2)
  )
}

plotTheme <- function(base_size = 12) {
  theme(
    text = element_text( color = "black"),
    plot.title = element_text(size = 14,colour = "black"),
    plot.subtitle = element_text(face="italic"),
    plot.caption = element_text(hjust=0),
    axis.ticks = element_blank(),
    panel.background = element_blank(),
    panel.grid.major = element_line("grey80", size = 0.1),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(colour = "black", fill=NA, size=2),
    strip.background = element_rect(fill = "grey80", color = "white"),
    strip.text = element_text(size=12),
    axis.title = element_text(size=12),
    axis.text = element_text(size=10),
    plot.background = element_blank(),
    legend.background = element_blank(),
    legend.title = element_text(colour = "black", face = "italic"),
    legend.text = element_text(colour = "black", face = "italic"),
    strip.text.x = element_text(size = 14)
  )
}

palette5 <- c("#25CB10", "#5AB60C", "#8FA108",   "#C48C04", "#FA7800")

qBr <- function(df, variable, rnd) {
  if (missing(rnd)) {
    as.character(quantile(round(df[[variable]],0),
                          c(.01,.2,.4,.6,.8), na.rm=T))
  } else if (rnd == FALSE | rnd == F) {
    as.character(formatC(quantile(df[[variable]]), digits = 3),
                          c(.01,.2,.4,.6,.8), na.rm=T)
  }
}

q5 <- function(variable) {as.factor(ntile(variable, 5))}

nn_function <- function(measureFrom,measureTo,k) {
  measureFrom_Matrix <- as.matrix(measureFrom)
  measureTo_Matrix <- as.matrix(measureTo)
  nn <-   
    get.knnx(measureTo, measureFrom, k)$nn.dist
    output <-
      as.data.frame(nn) %>%
      rownames_to_column(var = "thisPoint") %>%
      gather(points, point_distance, V1:ncol(.)) %>%
      arrange(as.numeric(thisPoint)) %>%
      group_by(thisPoint) %>%
      summarize(pointDistance = mean(point_distance)) %>%
      arrange(as.numeric(thisPoint)) %>% 
      dplyr::select(-thisPoint) %>%
      pull()
  
  return(output)  
}
```

## DATA WRANGLING
```{r read_data}
miamiRaw <- st_read('studentsData.geojson')

census_api_key("61f5998ae3ee7a7ab62b29f55769a3b864515ac4", overwrite = TRUE, install = TRUE)
readRenviron("~/.Renviron")


tracts18_MDCounty <- 
  get_acs(geography = "tract", variables = c("B01003_001E","B02001_002E", "B02001_003E", 
                                             "B02001_004E", "B02001_005E", "B25064_001E", 
                                             "B25005_001E", "B19013_001E", "B06012_002E",
                                             "B15002_032E", "B15002_015E", "B25001_001E"), 
          year=2018, state=12, county=086, geometry=T, output = 'wide') %>%   
          st_transform('ESRI:102658') %>%
          rename(TotalPop = B01003_001E, 
                 White = B02001_002E,
                 AfrAmerican = B02001_003E,
                 AmNative = B02001_004E,
                 Asian = B02001_005E,
                 MedGrossRent = B25064_001E,
                 VacantLiveElwh = B25005_001E,
                 MedHHInc.inf = B19013_001E, 
                 TotalPoverty = B06012_002E,
                 FemaleBachelorsDeg = B15002_032E, 
                 MaleBachelorsDeg = B15002_015E,
                 TotalHUnits = B25001_001E) %>%
  dplyr::select(-NAME, -starts_with("B")) %>%
  mutate(pctWhite = ifelse(TotalPop > 0, White / TotalPop, 0),
         pctAfrAm = ifelse(TotalPop > 0, AfrAmerican / TotalPop, 0),
         pctAmNa = ifelse(TotalPop > 0, AmNative / TotalPop, 0),
         pctAsian = ifelse(TotalPop > 0, Asian / TotalPop, 0),
         pctVacantLiveElwh = ifelse(TotalHUnits > 0, VacantLiveElwh / TotalHUnits, 0),
         pctBachelors = ifelse(TotalPop > 0, ((FemaleBachelorsDeg + MaleBachelorsDeg) / TotalPop), 0),
         pctPoverty = ifelse(TotalPop > 0, TotalPoverty / TotalPop, 0),
         year = "2018") %>%
  dplyr::select(-White, -AfrAmerican, -AmNative, -Asian, 
                -TotalHUnits, -VacantLiveElwh, -FemaleBachelorsDeg, 
                -MaleBachelorsDeg, -TotalPoverty)
```

